In [1]:
import math
import numpy as np
import matplotlib.pyplot as plt

from skimage import data
from skimage import transform

In [11]:
tform = transform.SimilarityTransform(scale=1)

print(tform.params)

coord = [1, 0]
print(tform(coord))
print(tform.inverse(tform(coord)))



[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[1. 0.]]
[[1. 0.]]
